## docker-compose up 
name: cr7imports

volumes:
   prometheus-data:
   grafana-data:

networks:
    aw-network:
     driver: bridge		

services:

  cr7ImportsAPI:
    container_name: cr7ImportsAPI
    image: openjdk:8
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_BOOT_ENVIRONMENT=Production
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal;databaseName=Cr7Imports;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=Banana!90
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8088:8080"
    volumes:
      - ./target/cr7-api-imports.jar:/usr/src/app/cr7-api-imports.jar
    working_dir: /usr/src/app
    command: ["java", "-jar", "cr7-api-imports.jar"]

  webServiceCR7:
    container_name: webServiceCR7
    image: openjdk:8
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_BOOT_ENVIRONMENT=Production
    ports:
      - "8089:8080"
    volumes:
      - ./target/web-service-cr7imports.jar:/usr/src/app/web-service-cr7imports.jar
    working_dir: /usr/src/app
    command: ["java", "-jar", "web-service-cr7imports.jar"]

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/users.yml:/data/users.yml
    ports:
      - "9999:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
 
  prometheus:
     container_name: prometheus
     image: prom/prometheus:latest	  
     volumes: 
       - ./docker/prometheus.yml:/data/prometheus.yml
       - prometheus-data:/prometheus
     networks: 
       - aw-network
     ports: 
       - "9090:9090"  

  grafana:
     container_name: grafana
     image: grafana/grafana:latest
     ports:
       - "3000:3000"
     networks: 
       - aw-network