global:
  scrape_interval: 5s  

scrape_configs:
  - job_name: "Api-job"
    metrics_path: "/apicr7imports/actuator/prometheus"
    static_configs:  
      - targets: ["host.docker.internal:8088"]
        labels:
          application: "cr7ImportsAPI"  
