## docker-compose up 
version: '3'
services:
  Api:
    image: openjdk:8
    restart: always
    container_name: cr7ImportsAPI
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_BOOT_ENVIRONMENT=Production
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal;databaseName=Cr7Imports;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=MyPassword123#
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8088:8080"
    volumes:
      - ./target/api-cr7-imports-0.0.1-SNAPSHOT.jar:/usr/src/app/api-cr7-imports-0.0.1-SNAPSHOT.jar
    working_dir: /usr/src/app
    command: ["java", "-jar", "api-cr7-imports-0.0.1-SNAPSHOT.jar"]
    networks:
      - my-network  # Adicionando o serviço à rede my-network

  web_service:
    image: openjdk:8
    restart: always
    container_name: webServiceCR7
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_BOOT_ENVIRONMENT=Production
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://host.docker.internal;databaseName=Cr7Imports;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=MyPassword123#
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - API_URL=http://localhost:8088	  
    ports:
      - "8089:8080"
    depends_on:
      - Api	  
    volumes:
      - ./target/webServiceCR7-0.0.1-SNAPSHOT.jar:/usr/src/app/webServiceCR7-0.0.1-SNAPSHOT.jar
    working_dir: /usr/src/app
    command: ["java", "-jar", "webServiceCR7-0.0.1-SNAPSHOT.jar"]
    networks:
      - my-network  # Adicionando o serviço à rede my-network

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/users.yml:/data/users.yml
    ports:
      - "9999:8080"
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    networks:
      - my-network  # Adicionando o serviço à rede my-network

networks:
  my-network:
    driver: bridge