name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      working-directory: /home/runner/work/ProjetoIntegradorIIApiRest/ProjetoIntegradorIIApiRest
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      working-directory: /home/runner/work/ProjetoIntegradorIIApiRest/ProjetoIntegradorIIApiRest
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        # Tag the image with 1.0
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:latest ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:1.0

        # Push the 1.0 tag to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:1.0

        # Optionally, you can also push the image as 'latest'
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:1.0 ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:${{ github.run_id }}

