name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Application JAR
      working-directory: /home/runner/work/ProjetoIntegradorIIApiRest/ProjetoIntegradorIIApiRest
      run: mvn clean package -DskipTests

    - name: Build Docker Image
      run: |
        # Build Docker image directly
        docker build -t api-cr7-imports:latest -f /home/runner/work/ProjetoIntegradorIIApiRest/ProjetoIntegradorIIApiRest/Dockerfile .

    - name: Tag and Push Docker Image
      run: |
        # Tag the image with a unique identifier based on the GitHub Actions run ID
        docker tag api-cr7-imports:latest ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:${{ github.run_id }}

        # Push the tagged image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/api-cr7-imports:${{ github.run_id }}
